### PR TITLE
Increase wait time for Window init (50 was 25) in Trakt Dashboard

### PR DESCRIPTION
**Pull request by andrewjswan**

### CODE REVIEW

**Comment by andrewjswan** [comment]
IMHO Best in Skin settings .xml

**Comment by damienhaynes** [comment]
Okay sounds good, do you want to make that change if you're comfortable?

**Comment by andrewjswan** [comment]
I’m not sure that I’ll figure out where to do it better, I’m not a guru in С#. If possible, do it yourself. Thanks.

**Comment by damienhaynes** [comment]
https://github.com/trakt/Trakt-for-Mediaportal/pull/121

**Pull request closed without merging**
